apiVersion: apps/v1
kind: Deployment
metadata:
  name: mohd-capstone
  labels:
    app: mohd-capstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mohd-capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mohd-capstone
  labels:
    app: mohd-capstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mohd-capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mohd-capstone
    spec:
      containers:
        - image: mohamedsgap/mohd-capstone
          imagePullPolicy: Always
          name: mohd-capstone
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mohd-capstone
  labels:
    app: mohd-capstone
spec:
  type: LoadBalancer
  selector:
    app: mohd-capstone
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
